export declare const SOCIAL: {
    facebook: string;
    twitter: string;
    dribbble: string;
};
export declare const THEME: {
    primary: string;
    primaryDark: string;
    primaryLight: string;
    primaryBright: string;
    info: string;
    infoDark: string;
    infoLight: string;
    infoBright: string;
    danger: string;
    dangerDark: string;
    dangerLight: string;
    dangerBright: string;
    warning: string;
    warningDark: string;
    warningLight: string;
    warningBright: string;
    success: string;
    successDark: string;
    successLight: string;
    successBright: string;
};
export declare const COMPONENTS: {
    input: string;
    placeholder: string;
    navbar: string;
    block: string;
    icon: string;
};
export declare const SHADOWS: {
    default: {
        boxShadow: string;
        elevation: number;
        shadowColor: string;
        shadowOffset: {
            width: number;
            height: number;
        };
        shadowOpacity: number;
        shadowRadius: number;
    };
    strong: {
        boxShadow: string;
        elevation: number;
        shadowColor: string;
        shadhowOffset: {
            width: number;
            height: number;
        };
        shadowOpacity: number;
        shadowRadius: number;
    };
};
export declare const BASE: {
    white: string;
    black: string;
    grey: string;
    muted: string;
    transparent: string;
    neutral: (opacity?: number) => string;
};
export declare const DARK_MODE: {
    facebook: string;
    twitter: string;
    dribbble: string;
    primary: string;
    primaryDark: string;
    primaryLight: string;
    primaryBright: string;
    info: string;
    infoDark: string;
    infoLight: string;
    infoBright: string;
    danger: string;
    dangerDark: string;
    dangerLight: string;
    dangerBright: string;
    warning: string;
    warningDark: string;
    warningLight: string;
    warningBright: string;
    success: string;
    successDark: string;
    successLight: string;
    successBright: string;
    input: string;
    placeholder: string;
    navbar: string;
    block: string;
    icon: string;
    background: string;
    text: string;
    white: string;
    black: string;
    grey: string;
    muted: string;
    transparent: string;
    neutral: (opacity?: number) => string;
};
export declare const LIGHT_MODE: {
    facebook: string;
    twitter: string;
    dribbble: string;
    primary: string;
    primaryDark: string;
    primaryLight: string;
    primaryBright: string;
    info: string;
    infoDark: string;
    infoLight: string;
    infoBright: string;
    danger: string;
    dangerDark: string;
    dangerLight: string;
    dangerBright: string;
    warning: string;
    warningDark: string;
    warningLight: string;
    warningBright: string;
    success: string;
    successDark: string;
    successLight: string;
    successBright: string;
    input: string;
    placeholder: string;
    navbar: string;
    block: string;
    icon: string;
    background: string;
    text: string;
    white: string;
    black: string;
    grey: string;
    muted: string;
    transparent: string;
    neutral: (opacity?: number) => string;
};
declare const _default: {
    LIGHT_MODE: {
        facebook: string;
        twitter: string;
        dribbble: string;
        primary: string;
        primaryDark: string;
        primaryLight: string;
        primaryBright: string;
        info: string;
        infoDark: string;
        infoLight: string;
        infoBright: string;
        danger: string;
        dangerDark: string;
        dangerLight: string;
        dangerBright: string;
        warning: string;
        warningDark: string;
        warningLight: string;
        warningBright: string;
        success: string;
        successDark: string;
        successLight: string;
        successBright: string;
        input: string;
        placeholder: string;
        navbar: string;
        block: string;
        icon: string;
        background: string;
        text: string;
        white: string;
        black: string;
        grey: string;
        muted: string;
        transparent: string;
        neutral: (opacity?: number) => string;
    };
    DARK_MODE: {
        facebook: string;
        twitter: string;
        dribbble: string;
        primary: string;
        primaryDark: string;
        primaryLight: string;
        primaryBright: string;
        info: string;
        infoDark: string;
        infoLight: string;
        infoBright: string;
        danger: string;
        dangerDark: string;
        dangerLight: string;
        dangerBright: string;
        warning: string;
        warningDark: string;
        warningLight: string;
        warningBright: string;
        success: string;
        successDark: string;
        successLight: string;
        successBright: string;
        input: string;
        placeholder: string;
        navbar: string;
        block: string;
        icon: string;
        background: string;
        text: string;
        white: string;
        black: string;
        grey: string;
        muted: string;
        transparent: string;
        neutral: (opacity?: number) => string;
    };
    SHADOWS: {
        default: {
            boxShadow: string;
            elevation: number;
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
        };
        strong: {
            boxShadow: string;
            elevation: number;
            shadowColor: string;
            shadhowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
        };
    };
};
export default _default;
//# sourceMappingURL=colors.d.ts.map